@startuml
title
    Keyple - keyple-card-calypso-java-lib - 2.2.+ (2022-10-26)
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    __Colors legend__ :
    * __External API references__ :
    ** <back:yellow>**calypsonet-terminal-reader-java-api**</back>
    ** <back:pink>**calypsonet-terminal-calypso-java-api**</back>
    ** <back:cyan>**keyple-common-java-api**</back>
    ** <back:orange>**keyple-service-resource-java-lib**</back>
end legend

package "org.eclipse.keyple.card.calypso" as calypso {
    +class "<<<back:cyan>KeypleCardExtension</back>>>\n**final** CalypsoExtensionService" as CalypsoExtensionService {
        --
        +{static} CalypsoExtensionService getInstance ()

        +<back:pink>SearchCommandData</back> createSearchCommandData ()
        +<back:pink>BasicSignatureComputationData</back> createBasicSignatureComputationData ()
        +<back:pink>TraceableSignatureComputationData</back> createTraceableSignatureComputationData ()
        +<back:pink>BasicSignatureVerificationData</back> createBasicSignatureVerificationData ()
        +<back:pink>TraceableSignatureVerificationData</back> createTraceableSignatureVerificationData ()

        +<back:pink>CalypsoCardSelection</back> createCardSelection ()
        +<back:pink>CalypsoSamSelection</back> createSamSelection ()
        
        +<back:orange>CardResourceProfileExtension</back> createSamResourceProfileExtension (<back:pink>CalypsoSamSelection</back> calypsoSamSelection)

        +<back:pink>CardSecuritySetting</back> createCardSecuritySetting ()
        +<back:pink>CardTransactionManager</back> createCardTransaction (<back:yellow>CardReader</back> cardReader, <back:pink>CalypsoCard</back> calypsoCard, <back:pink>CardSecuritySetting</back> cardSecuritySetting)
        +<back:pink>CardTransactionManager</back> createCardTransactionWithoutSecurity (<back:yellow>CardReader</back> cardReader, <back:pink>CalypsoCard</back> calypsoCard)

        +<back:pink>SamSecuritySetting</back> createSamSecuritySetting ()
        +<back:pink>SamTransactionManager</back> createSamTransaction (<back:yellow>CardReader</back> samReader, <back:pink>CalypsoSam</back> calypsoSam, <back:pink>SamSecuritySetting</back> samSecuritySetting)
        +<back:pink>SamTransactionManager</back> createSamTransactionWithoutSecurity (<back:yellow>CardReader</back> samReader, <back:pink>CalypsoSam</back> calypsoSam)
        '+void forceCardProductType (<back:pink>CalypsoCard.ProductType</back> productType, <back:pink>CalypsoCard</back> calypsoCard)
        '+void checkSamExtension (CalypsoSamExtension samExtension)

        -- **KeypleCardExtension** --
        +String getCommonApiVersion ()
        +String getReaderApiVersion ()
        +String getCardApiVersion ()
    }

    'package spi {
    '    +interface CalypsoSamExtension {
    '        +String getCalypsoLibVersion ()
    '    }
    '}
}

' Associations

'CalypsoExtensionService ..> CalypsoSamExtension #C_USE : use >

' == LAYOUT ==

' == STYLE ==

package calypso #C_GREY1 {}
'package spi #C_GREY2 {}

@enduml